const WNA = [
    {
      "no_permohonan": 31020113190008,
      "sub_tahapan": "SELESAI",
      "dokim_no": "2B11G20006AT",
      "dokim_mulai": "2019-05-16",
      "dokim_akhir": "2019-05-27",
      "nama_depan": "BAOSHENG",
      "nama_belakang": "YANG",
      "nama_pemohon": "BAOSHENG YANG",
      "jenis_kelamin": "P",
      "tempat_lahir": "HENAN",
      "tgl_lahir": "1987-10-03",
      "niora": "JDSAB52689",
      "email": "asf@yahoo.com",
      "nama_layanan": "PERPANJANGAN ITK Ke 1 PEMBICARAAN BISNIS 60 HARI",
      "tujuan": "PEMBICARAAN BISNIS",
      "waktu": "60 HARI",
      "ntb": "",
      "ntpn": "",
      "waktu_bayar": "",
      "status_sipil": "KAWIN",
      "kebangsaan": "CHINA",
      "no_paspor": "G48910348",
      "alamat_pemohon": "DUSUN XIV DESA PALUH KURAU",
      "kecamatan": "MEDAN DELI",
      "kabupaten_kota": "KOTA MEDAN",
      "pekerjaan": "Businessman",
      "tanggal_permohonan": "2019-04-23 06:09:32",
      "petugas1": "Dedy Depsa Ginting",
      "terakhir_dilayani": "2019-05-16 02:37:42",
      "petugas2": "",
      "no_penguasaan": "",
      "no_sk_ditjenim": "",
      "no_sk_kanwil": "",
      "no_surat_permohonan": "",
      "no_surat_permohonan_kanwil": "",
      "no_surat_permohonan_kanim": "",
      "sponsor_nama": "TENNY JEMIYEN",
      "sponsor_alamat": "JL. PUKAT VIII NO. 25A KEL. BANTAN TIMUR",
      "sponsor_kota": "KOTA MEDAN",
      "sponsor_telepon": 0
    }
  ]
export default WNA;